### ISSUE TITLE
README needs more details

### ISSUE THREAD

**Issue by asamiz** [musab-r/React-Native-Hijri-Calendar#1]
Hi, 
Thank you so much for your efforts.
Can you please provide an example on how we can use this compnent?

**Comment by musab-r** [comment]
> Hi, Thank you so much for your efforts. Can you please provide an example on how we can use this compnent?
Hi,

As this is not complete package, didn't get time to make one. You need to add these file either from here or alternative source and use it but if you need to add features or require some modification then go to the datepicker file and apply manually because package is supposed to be for React only. 

FYI I was required to modify this props.navigationDate. 
I think that might work as well [link](https://snyk.io/advisor/npm-package/react-native-hijri-date-picker-android).
